// <auto-generated />
namespace CheckIt.Domain.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.2-21211")]
    public sealed partial class UserIsTemporal : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UserIsTemporal));
        
        string IMigrationMetadata.Id
        {
            get { return "201403070352370_User-IsTemporal"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
