//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CheckIt.Entities
{
    using System;
    
    public enum AccountStatus : int
    {
        Created = 0,
        Verified = 1,
        Active = 2,
        Suspended = 3,
        Closed = 4
    }
}
