//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CheckIt.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public Account()
        {
            this.DefaultLanguage = "en";
            this.Folders = new HashSet<Folder>();
            this.Favorites = new HashSet<Favorite>();
        }
    
        public int AccountId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Ocupation { get; set; }
        public string Industry { get; set; }
        public AccountStatus Status { get; set; }
        public string DefaultLanguage { get; set; }
    
        public virtual ICollection<Folder> Folders { get; set; }
        public virtual ICollection<Favorite> Favorites { get; set; }
        public virtual Country Country { get; set; }
        public virtual User User { get; set; }
    }
}
