//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CheckIt.Entities
{
    using System;
    using System.Collections.Generic;
    
    public abstract partial class Answer
    {
        public System.Guid AnswerId { get; set; }
        public System.DateTime Created { get; set; }
        public System.DateTime Modified { get; set; }
        public byte[] Value { get; set; }
    
        public virtual Item Item { get; set; }
        public virtual User User { get; set; }
    }
}
