//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CheckIt.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category
    {
        public Category()
        {
            this.SubCategories = new HashSet<Category>();
            this.Checklists = new HashSet<Checklist>();
        }
    
        public int CategoryId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
    
        public virtual Area Area { get; set; }
        public virtual ICollection<Category> SubCategories { get; set; }
        public virtual Category SuperCategory { get; set; }
        public virtual ICollection<Checklist> Checklists { get; set; }
    }
}
