//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CheckIt.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Checklist
    {
        public Checklist()
        {
            this.Hints = 0;
            this.Rating = 0;
            this.Language = "en";
            this.Share = new HashSet<Share>();
            this.Sections = new HashSet<Section>();
            this.Keywords = new HashSet<Keyword>();
        }
    
        public System.Guid ChecklistId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Reference1 { get; set; }
        public string Reference2 { get; set; }
        public long Hints { get; set; }
        public short Rating { get; set; }
        public string Language { get; set; }
        public System.DateTime Created { get; set; }
        public System.DateTime Modified { get; set; }
        public ItemStatus Status { get; set; }
    
        public virtual User User { get; set; }
        public virtual ICollection<Share> Share { get; set; }
        public virtual ICollection<Section> Sections { get; set; }
        public virtual Category Category { get; set; }
        public virtual ICollection<Keyword> Keywords { get; set; }
    }
}
