//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CheckIt.Entities
{
    using System;
    using System.Collections.Generic;
    
    public abstract partial class Item
    {
        public Item()
        {
            this.Hints = 0;
            this.Keywords = new HashSet<Keyword>();
            this.Answers = new HashSet<Answer>();
        }
    
        public System.Guid ItemId { get; set; }
        public string Content { get; set; }
        public string Description { get; set; }
        public string Reference1 { get; set; }
        public string Reference2 { get; set; }
        public long Hints { get; set; }
        public ItemStatus Status { get; set; }
        public ItemType Type { get; set; }
    
        public virtual Section Section { get; set; }
        public virtual ICollection<Keyword> Keywords { get; set; }
        public virtual ICollection<Answer> Answers { get; set; }
    }
}
