//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CheckIt.Entities
{
    using System;
    
    public enum ItemStatus : int
    {
        Created = 0,
        Cheked = 1,
        Approved = 2,
        Dismissed = 3
    }
}
