//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CheckIt.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Keyword
    {
        public Keyword()
        {
            this.Language = "en";
            this.Hints = 0;
            this.Checklists = new HashSet<Checklist>();
            this.Sections = new HashSet<Section>();
            this.Items = new HashSet<Item>();
            this.RelatedKeywords = new HashSet<Keyword>();
            this.ReferencedKeywords = new HashSet<Keyword>();
        }
    
        public System.Guid KeywordId { get; set; }
        public string Word { get; set; }
        public string Language { get; set; }
        public long Hints { get; set; }
    
        public virtual ICollection<Checklist> Checklists { get; set; }
        public virtual ICollection<Section> Sections { get; set; }
        public virtual ICollection<Item> Items { get; set; }
        public virtual ICollection<Keyword> RelatedKeywords { get; set; }
        public virtual ICollection<Keyword> ReferencedKeywords { get; set; }
    }
}
