//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CheckIt.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CheckItContext : DbContext
    {
        public CheckItContext()
            : base("name=CheckItContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Checklist> Checklists { get; set; }
        public virtual DbSet<Section> Sections { get; set; }
        public virtual DbSet<Item> Items { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Account> Accounts { get; set; }
        public virtual DbSet<Category> Categorys { get; set; }
        public virtual DbSet<Keyword> Keywords { get; set; }
        public virtual DbSet<Favorite> Favorites { get; set; }
        public virtual DbSet<Area> Areas { get; set; }
        public virtual DbSet<Folder> Folders { get; set; }
        public virtual DbSet<Share> Shares { get; set; }
        public virtual DbSet<Answer> Answers { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
    }
}
