//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CheckIt.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Section
    {
        public Section()
        {
            this.Hints = 0;
            this.Items = new HashSet<Item>();
            this.Keywords = new HashSet<Keyword>();
        }
    
        public System.Guid SectionId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public long Hints { get; set; }
        public ItemStatus Status { get; set; }
    
        public virtual Checklist Checklist { get; set; }
        public virtual ICollection<Item> Items { get; set; }
        public virtual ICollection<Keyword> Keywords { get; set; }
    }
}
