//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CheckIt.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Checklists = new HashSet<Checklist>();
            this.Share = new HashSet<Share>();
            this.Answers = new HashSet<Answer>();
        }
    
        public string Id { get; set; }
        public string PasswordHash { get; set; }
        public string SecurityStamp { get; set; }
        public string UserName { get; set; }
        public string Discriminator { get; set; }
    
        public virtual ICollection<Checklist> Checklists { get; set; }
        public virtual ICollection<Share> Share { get; set; }
        public virtual Account Account { get; set; }
        public virtual ICollection<Answer> Answers { get; set; }
    }
}
